
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[180] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   30,   28,    1,    2,   28,   28,   28,   25,
       25,   27,    6,    1,    5,    6,    6,    6,    6,    6,
        6,   17,   17,   16,   22,   24,   23,   23,   28,   14,
       13,   13,   12,    1,    0,   25,   25,   26,   26,    0,
        0,    0,    0,    3,   26,   25,    9,   25,    0,   27,
       10,   11,    6,    1,    4,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,   17,    0,   16,   23,    0,   13,   13,   13,
       13,    0,   12,    0,    0,   26,    0,    0,    0,    0,

        0,   26,   26,   25,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,   17,   23,    0,   13,   25,
       26,   26,    0,    0,    0,    0,    0,    6,    6,    6,
        6,    6,    6,    6,    6,   13,   26,   26,    7,    8,
        0,    0,   26,    6,    6,    6,    6,    6,    6,    6,
       26,   26,   15,    0,   26,    6,    6,    6,    6,    6,
       26,   18,   20,   21,   19,   26,    6,    6,    6,    6,
        6,    6,   26,   26,    6,    6,   26,    6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    6,    7,    1,    7,    8,    9,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
       13,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   20,   20,   21,   20,   22,   23,   20,
       24,   25,   20,   26,   20,   20,   27,   28,   29,   20,
        1,    1,    1,    1,    1,    1,   30,   31,   30,   30,

       32,   19,   20,   20,   20,   20,   20,   33,   20,   20,
       20,   20,   33,   20,   20,   20,   20,   20,   33,   28,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[34] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    1,    1,    3,
        3,    4,    4,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    3,
        3,    3,    4
    } ;

static yyconst flex_int16_t yy_base[197] =
    {   0,
        0,   13,   26,   39,   52,   65,  423,  422,   74,   76,
       87,  100,  425,  719,  416,  719,   72,  104,  411,  122,
      383,  104,    0,  408,  399,  115,  146,  401,  164,  378,
      197,  108,  377,  115,  719,  719,  137,  376,  134,    0,
      203,  375,  126,  400,  141,  149,  362,  227,  358,  361,
      369,  359,  360,  719,  156,  349,  719,  719,    0,  156,
      719,  719,    0,  374,  719,  170,  229,  232,  251,  274,
      351,  357,  347,  345,  297,  330,    0,    0,  320,  352,
        0,    0,  327,    0,  174,  321,    0,  237,  319,  318,
      719,    0,  177,    0,  183,  719,    0,  328,  318,  317,

      321,  130,  323,  358,  382,  197,    0,  405,  311,  301,
      299,  303,  428,  451,  476,  502,  528,    0,  554,  580,
      206,  152,  304,  307,  292,  290,    0,  606,  209,  164,
      294,  295,  279,  268,  630,  655,  253,  256,  719,  719,
      251,  255,  194,  267,  271,    0,    0,  229,  240,  203,
      210,  222,  719,  275,  287,  204,  300,    0,  299,  330,
      240,  719,  719,  719,  719,  242,  357,    0,    0,    0,
        0,  362,  265,  284,  236,  377,  290,  255,  719,  688,
      692,  696,  700,  702,  706,  710,  712,  714,  200,  197,
      175,  170,  151,  132,  128,  121

    } ;

static yyconst flex_int16_t yy_def[197] =
    {   0,
      180,  180,  181,  181,  182,  182,    2,    2,    2,    2,
      183,  183,  179,  179,  179,  179,  179,  179,  179,  179,
       20,  184,  185,  185,  179,  185,  185,  185,  185,   29,
      186,   20,   32,  187,  179,  179,   32,   37,  179,   18,
      179,   41,  188,  179,  179,   37,   46,  179,   48,  179,
      179,  179,  179,  179,   49,   20,  179,  179,  189,  184,
      179,  179,  185,  185,  179,  185,   29,   29,  185,  185,
      185,  185,  185,  185,  185,   29,  185,  185,  185,  186,
      185,  185,   32,  190,  187,   37,  191,   41,   88,   41,
      179,  192,  188,  193,  179,  179,  194,  179,  179,  179,

      179,   55,   55,  189,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,   79,  190,  191,  195,  192,  193,
      179,  194,  179,  179,  179,  179,  196,  105,  185,  108,
      185,  185,  185,  185,  185,  195,  179,  194,  179,  179,
      179,  179,  196,  185,  108,  185,  185,  185,  185,  135,
      179,  138,  179,  179,  196,  185,  108,  185,  185,  135,
      138,  179,  179,  179,  179,  155,  108,  185,  185,  185,
      185,  135,  138,  155,  108,  135,  155,  135,    0,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179

    } ;

static yyconst flex_int16_t yy_nxt[753] =
    {   0,
       14,   15,   16,   14,   14,   14,   17,   18,   19,   20,
       21,   14,   14,   14,   15,   16,   14,   14,   14,   17,
       18,   19,   20,   21,   14,   14,   23,   24,   16,   23,
       23,   25,   26,   27,   28,   29,   30,   23,   23,   23,
       24,   16,   23,   23,   25,   26,   27,   28,   29,   30,
       23,   23,   14,   15,   16,   14,   14,   14,   17,   18,
       19,   32,   33,   14,   14,   14,   15,   16,   14,   14,
       14,   17,   18,   19,   32,   33,   14,   14,   36,   45,
       36,   46,   47,   37,   38,   37,   38,   14,   15,   16,
       14,   14,   14,   39,   40,   19,   41,   42,   14,   14,

       14,   15,   16,   14,   14,   14,   39,   40,   19,   41,
       42,   14,   14,   48,   49,   61,   62,   83,   83,   50,
       51,   52,   66,  143,   67,   68,   61,   62,   53,   55,
      136,   56,   56,   57,  122,   84,   58,   61,   62,  103,
       58,   45,   58,   88,   89,   58,   86,   86,   58,   59,
       48,   49,   58,  120,   58,   69,   70,  127,   47,   47,
      179,   71,   72,   73,   87,  102,  103,   61,   62,  138,
       74,   75,  119,   76,   76,   77,   94,  117,   78,   69,
       70,  145,   78,  138,   78,   61,   62,   78,   61,   62,
       78,   79,  121,  121,   78,  145,   78,   63,   63,  116,

       63,   63,  104,   63,   63,   63,  129,  129,   81,   82,
       55,  155,   90,   90,   57,  137,  137,   91,  144,  144,
      160,   91,  107,   91,   96,  155,   91,  107,   96,   91,
       92,  161,  161,   91,  160,   91,   49,   49,   68,   68,
       63,   68,   68,   63,   95,   96,   89,   89,  179,  173,
      173,  174,  174,  145,   97,  159,  105,  158,   95,   63,
       70,   70,  151,  151,  118,  152,  152,  145,  106,  107,
      154,   96,  160,  138,  122,  122,  156,  156,  108,  153,
      157,  157,  106,   70,   70,  107,  160,  138,  145,  162,
      149,  106,  107,  177,  177,  163,  166,  166,  164,  143,

      143,  165,  145,  148,  155,  106,  113,  114,  147,  167,
      167,  146,  142,  168,  106,  107,  141,  145,  155,  169,
      140,  139,  170,  134,  133,  171,  132,  131,  106,  115,
      115,  145,  103,  115,  115,  115,  115,  115,  115,  172,
      172,  126,  125,  124,  123,  179,  179,  160,  179,  115,
      115,  115,   63,   63,  179,   63,   63,   63,   63,   63,
       63,  160,  112,   81,   82,   55,  175,  175,  111,   57,
      110,  176,  176,  109,  145,   64,  179,  101,   58,  160,
      100,   58,   99,   98,   58,  179,  178,  178,  145,  179,
       58,  128,  128,  160,  160,  128,  128,  128,  128,  128,

      128,   44,  179,  179,  179,   63,   54,   65,  160,   64,
      179,  128,  128,  128,  130,  130,   54,   44,  130,  130,
      130,  130,  130,  130,  179,   35,   35,  179,  179,  179,
      179,  179,  179,  179,  130,  130,  130,  114,  114,  179,
      179,  179,  179,  179,  179,  106,  107,  179,  179,  179,
      179,  179,  179,  179,  179,  135,  179,  179,  179,  106,
      114,  114,  179,  179,  179,  179,  179,  179,  106,  107,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  106,   75,  179,  179,  179,   77,  179,  179,
      179,  179,  179,  179,  179,  179,   78,  179,  179,   78,

      179,  179,   78,  179,  179,  179,  179,  179,   78,   55,
      179,  179,  179,   57,  179,  179,  179,  179,  179,  179,
      179,  179,   58,  179,  179,   58,  179,  179,   58,  179,
      179,  179,  179,  179,   58,   55,  179,  179,  179,   57,
      179,  179,  179,  179,  179,  179,  179,  179,   58,  179,
      179,   58,  179,  179,   58,  179,  179,  179,  179,  179,
       58,   55,  179,  179,  179,   57,  179,  179,  179,  179,
      179,  179,  179,  179,   91,  179,  179,   91,  179,  179,
       91,  179,  179,  179,  179,  179,   91,   55,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,

       58,  179,  179,   58,  179,  179,   58,  179,  179,  179,
      179,  179,   58,   75,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,   78,  179,  179,   78,
      179,  179,   78,  179,  179,  179,  179,  179,   78,  150,
      150,  179,  179,  150,  150,  150,  150,  150,  150,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  150,
      150,  150,   55,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,   91,  179,  179,   91,  179,
      179,   91,  179,  179,  179,  179,  179,   91,   22,   22,
       22,   22,   31,   31,   31,   31,   34,   34,   34,   34,

       43,   43,   43,   43,   60,   60,   63,  179,   63,   63,
       80,  179,   80,   80,   85,   85,   93,   93,   13,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179
    } ;

static yyconst flex_int16_t yy_chk[753] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    9,   17,
       10,   17,   17,    9,    9,   10,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   18,   18,   22,   22,   32,   32,   18,
       18,   18,   26,  196,   26,   26,   34,   34,   18,   20,
      195,   20,   20,   20,  194,   32,   20,   43,   43,  102,
       20,   39,   20,   39,   39,   20,   37,   37,   20,   20,
       45,   45,   20,  193,   20,   27,   27,  102,   46,   46,
       46,   27,   27,   27,   37,   55,   55,   60,   60,  122,
       27,   29,  192,   29,   29,   29,   46,  191,   29,   66,
       66,  130,   29,  122,   29,   85,   85,   29,   93,   93,
       29,   29,   95,   95,   29,  130,   29,   31,   31,  190,

       31,   31,  189,   31,   31,   31,  106,  106,   31,   31,
       41,  143,   41,   41,   41,  121,  121,   41,  129,  129,
      150,   41,  156,   41,  121,  143,   41,  129,  151,   41,
       41,  152,  152,   41,  150,   41,   48,   48,   67,   67,
       67,   68,   68,   68,   48,   48,   88,   88,   88,  161,
      161,  166,  166,  175,   48,  149,   67,  148,   48,   68,
       69,   69,  137,  137,   88,  138,  138,  175,   69,   69,
      142,  137,  178,  138,  173,  173,  144,  144,   69,  141,
      145,  145,   69,   70,   70,  144,  178,  138,  145,  154,
      134,   70,   70,  174,  174,  154,  155,  155,  154,  177,

      177,  154,  145,  133,  155,   70,   75,   75,  132,  157,
      157,  131,  126,  159,   75,   75,  125,  157,  155,  159,
      124,  123,  159,  112,  111,  159,  110,  109,   75,   79,
       79,  157,  103,   79,   79,   79,   79,   79,   79,  160,
      160,  101,  100,   99,   98,   90,   89,  160,   86,   79,
       79,   79,   80,   80,   83,   80,   80,   76,   80,   80,
       80,  160,   74,   80,   80,  104,  167,  167,   73,  104,
       72,  172,  172,   71,  167,   64,   56,   53,  104,  172,
       52,  104,   51,   50,  104,   49,  176,  176,  167,   47,
      104,  105,  105,  172,  176,  105,  105,  105,  105,  105,

      105,   44,   42,   38,   33,   30,   28,   25,  176,   24,
       21,  105,  105,  105,  108,  108,   19,   15,  108,  108,
      108,  108,  108,  108,   13,    8,    7,    0,    0,    0,
        0,    0,    0,    0,  108,  108,  108,  113,  113,    0,
        0,    0,    0,    0,    0,  113,  113,    0,    0,    0,
        0,    0,    0,    0,    0,  113,    0,    0,    0,  113,
      114,  114,    0,    0,    0,    0,    0,    0,  114,  114,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  114,  115,    0,    0,    0,  115,    0,    0,
        0,    0,    0,    0,    0,    0,  115,    0,    0,  115,

        0,    0,  115,    0,    0,    0,    0,    0,  115,  116,
        0,    0,    0,  116,    0,    0,    0,    0,    0,    0,
        0,    0,  116,    0,    0,  116,    0,    0,  116,    0,
        0,    0,    0,    0,  116,  117,    0,    0,    0,  117,
        0,    0,    0,    0,    0,    0,    0,    0,  117,    0,
        0,  117,    0,    0,  117,    0,    0,    0,    0,    0,
      117,  119,    0,    0,    0,  119,    0,    0,    0,    0,
        0,    0,    0,    0,  119,    0,    0,  119,    0,    0,
      119,    0,    0,    0,    0,    0,  119,  120,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      120,    0,    0,  120,    0,    0,  120,    0,    0,    0,
        0,    0,  120,  128,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  128,    0,    0,  128,
        0,    0,  128,    0,    0,    0,    0,    0,  128,  135,
      135,    0,    0,  135,  135,  135,  135,  135,  135,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  135,
      135,  135,  136,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  136,    0,    0,  136,    0,
        0,  136,    0,    0,    0,    0,    0,  136,  180,  180,
      180,  180,  181,  181,  181,  181,  182,  182,  182,  182,

      183,  183,  183,  183,  184,  184,  185,    0,  185,  185,
      186,    0,  186,  186,  187,  187,  188,  188,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "load.l"
#line 12 "load.l"
#include <ctype.h>
#include "envir.h"
#define	NO_MEMONIC	-1

extern Quad entry;

	/* function prototypes */
static int look_mem(), insert(), look_up();
static void fix_fwd(), put(),	put_here();	
static Quad get ();

	/* internal variables */
static int line_no = 1, size, arg_pos, yylval;

#define		CS	0
#define		DS	1
static int	csn = CS, rs =  CS;
static Quad	curr_pos = Q0, load_addr = Q0;
static struct { Quad	pos, load;} Sect[2] = {{Q0, Q0}, {Q0,Q0}};

struct Fnode { 
	Quad loc; 
	int size, sect; 
	struct Fnode *next;
};
typedef struct Fnode *Fptr;
typedef struct {
	char	name[15];
	Quad	value; 
	int	sect, decl_size;
	Fptr	fptr; /* nill ptr ==> no fwd refs */
} STentry;
static STentry	ST[1000] = {"<undef>", {-1,-1}, -1, 0, 0L};

 
#line 712 "<stdout>"

#define INITIAL 0
#define COM 1
#define N 2
#define R 3
#define RO 4
#define Q 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 48 "load.l"

#line 901 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 180 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 719 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "load.l"
{	/* white space */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 50 "load.l"
{	line_no ++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "load.l"
{	BEGIN (COM); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "load.l"
{	BEGIN (INITIAL); }
	YY_BREAK
case 5:
#line 54 "load.l"
case 6:
YY_RULE_SETUP
#line 54 "load.l"
{	/* all characters in comment*/ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "load.l"
{	Sect[csn].pos = curr_pos; Sect[csn].load = load_addr;
				csn = CS; 
				curr_pos = Sect[csn].pos; load_addr = Sect[csn].load; 
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "load.l"
{	Sect[csn].pos = curr_pos; Sect[csn].load = load_addr;
				csn = DS; 
				curr_pos = Sect[csn].pos; load_addr = Sect[csn].load; 
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "load.l"
{	yytext[--yyleng] = '\000'; 
				curr_pos = qadd (Strtoq(yytext), load_addr);
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "load.l"
{	int val; 
				yytext[--yyleng] = '\000'; 
				if ((val = look_up(yytext)) > 0) {	/* in ST */
					STentry *p = &ST[val];
					if (p->fptr == 0L)		/* no fwd ref ==> already defined */
						yyerror ("Warning: Duplicate definition");
					else {
						p->value = curr_pos; p->sect = csn; p->decl_size = 8;
						fix_fwd (p->fptr, curr_pos); p->fptr = 0L;
					}
				}
				else {		/* not in ST */
					STentry *p = &ST[insert(yytext)];
					p->value = curr_pos; p->sect = csn; p->decl_size = 8;
					p->fptr = 0L;
				}
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "load.l"
{	BEGIN (Q); yytext[--yyleng] = '\000';
				if ((yylval = look_up(yytext)) == 0) {
					yylval = insert(yytext); ST[yylval].fptr = 0L;
				}
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "load.l"
{	STentry *p = &ST[yylval], *q = &ST[look_up(yytext)];
				BEGIN (INITIAL);
				p->value = q->value; p->sect = q->sect;
				p->decl_size = q->decl_size;
				fix_fwd (p->fptr, p->value); p->fptr = 0L;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "load.l"
{	STentry *p = &ST[yylval]; char c = yytext[yyleng-1];
				BEGIN (INITIAL);
				p->value = Strtoq(yytext); p->decl_size = 2;
				if (isalpha(c)) switch (c) {
						case 'y': case 'Y': p->decl_size = 1; break;
						case 'w': case 'W': p->decl_size = 2; break;
						case 'l': case 'L': p->decl_size = 4; break;
						case 'q': case 'Q': p->decl_size = 8; break;
					}
				fix_fwd (p->fptr, p->value); p->fptr = 0L;
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 107 "load.l"
{	STentry *p = &ST[yylval];
				BEGIN INITIAL;
				p->value = curr_pos; p->sect = csn; p->decl_size = 8;
				fix_fwd (p->fptr, curr_pos); p->fptr = 0L;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 113 "load.l"
{	BEGIN (N); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 114 "load.l"
{	BEGIN (INITIAL); entry = ST[look_up(yytext)].value; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 115 "load.l"
{	BEGIN (INITIAL); entry = qadd (Strtoq(yytext), Sect[CS].load); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 117 "load.l"
{	BEGIN (R); size = 1; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 118 "load.l"
{	BEGIN (R); size = 2; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 119 "load.l"
{	BEGIN (R); size = 4; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "load.l"
{	BEGIN (R); size = 8; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "load.l"
{	BEGIN (RO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "load.l"
{	Quad loc; loc = Strtoq(yytext);
				put (csn, size, loc, qadd (get (csn, size, loc), Sect[rs].load));
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "load.l"
{	BEGIN (INITIAL);	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "load.l"
{	char c = yytext[yyleng-1]; int size = 0;
				Quad val; val = Strtoq (yytext);
				if (isalpha(c)) switch (c) {
						case 'y': case 'Y': size = 1; break;
						case 'w': case 'W': size = 2; break;
						case 'l': case 'L': size = 4; break;
						case 'q': case 'Q': size = 8; break;
						case 'f': case 'F': {
								union {float f; lword l;} u;
								if (strchr(yytext, '.') == 0L) break;
								yytext[yyleng-1]='\000';
								sscanf (yytext, "%f", &(u.f));
								val.bot = u.l; size = 4;
							}
							break;
					}
				put_here (val, size);
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 145 "load.l"
{	union { float f; lword l;} u; Quad v;
				if (toupper(yytext[yyleng-1])=='F')yytext[yyleng-1]='\000';
				sscanf (yytext, "%f", &(u.f)); v.bot = u.l;
				put_here (v, 4);
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 151 "load.l"
{	int	val;
				if ((val = look_mem (yytext)) != NO_MEMONIC) {
					put (csn, 1, curr_pos, i2q (yylval = val));
					curr_pos = qadd (curr_pos, q1);
					arg_pos = 0;
				}
				else	if ((val = look_up(yytext)) > 0) {	/*in ST */
					STentry *p = &ST[val];
					if ((arg_pos >= instrs[yylval].no_arg) && (csn==CS))
							yyerror ("Illegal Memonic");
					if (p->fptr == 0L) {		/* already defined */
						put_here (p->value, 0);
					}
					else {		/* add to fwd ref pointers */
						Fptr q = (Fptr)malloc(sizeof(struct Fnode));
						q->loc = curr_pos; q->sect = csn;
						q->size = 4; curr_pos = qadd (curr_pos, q4);
						q->next = p->fptr; p->fptr = q;
					}
				}
				else { 			/* not in ST */
					STentry *p = &ST[val = insert(yytext)];
					Fptr q = (Fptr)malloc(sizeof(struct Fnode));
					q->loc = curr_pos; q->sect = csn;
					q->size = 4; curr_pos = qadd (curr_pos, q4);
					q->next = 0L; p->fptr = q;
				}
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 180 "load.l"
{	yyerror ("Unknown Symbol"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 181 "load.l"
ECHO;
	YY_BREAK
#line 1224 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
case YY_STATE_EOF(N):
case YY_STATE_EOF(R):
case YY_STATE_EOF(RO):
case YY_STATE_EOF(Q):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 180 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 180 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 179);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 181 "load.l"


#include "S_instr.h"
#define SIsize (sizeof(S_instr)/sizeof(struct I))
static int look_mem(s)
char	s[];
{
	int i;
	for (i=0; i<SIsize; i++)
		if (strcmp(s, S_instr[i].name) == 0) return (S_instr[i].value);
	return NO_MEMONIC;
}

static int pos = 0;
static int insert(s)
char	s[];
{
	int i;
	for (i=1; i<= pos; i++)
		if (strcmp(s, ST[i].name)==0) {
			yyerror ("Symbol already defined"); return i;
		}
	pos ++; strcpy (ST[pos].name, s); return pos;
}
static int look_up(s)
char	s[];
{
	int i;
	for (i=1; i<= pos; i++)
		if (strcmp (s, ST[i].name) == 0) return i;
	return 0;
}
Quad symb_value (s)
char	s[];
{
	int	i = look_up (s);
	if (i == 0) printf ("Symbol %s not defined\n", s);
	else return ST[i].value;
	return q0;
}
void printST()
{
	int i=0;
	printf ("\n/* Symbols */\n");
	printf ("%-10s\t%-2s %-16s (%-6s) %s\n",
		"Name", "S", "Val-Hex", "  Dec", "Defined");
	for ( ; i <= pos; i++) {
		STentry *p = &ST[i];
		printf ("%-10s\t%2d %08x%08x (%06d) %s\n",
			p->name, p->sect, p->value.top, p->value.bot,
			p->value.bot, p->fptr==0L?"true":"false");
	}
}

static void fix_fwd(fptr, val)
Fptr fptr;
lword val;
{
	while (fptr != 0L) {
		Fptr n = fptr->next;
		put (fptr->sect, fptr->size, fptr->loc, val);
		free (fptr); fptr = n;
	}
}

static Quad get (sect, size, loc)
int	sect, size;
Quad	loc;
{
	Quad val; val.top = 0;
	if (sect == CS)
		switch (size) {
			case 1 : val.bot = get_code_byte (loc); break;
			case 2 : val.bot = get_code_word (loc); break;
			case 4 : val.bot = get_code_long (loc); break;
			case 8 : val = get_code_quad (loc); break;
		}
	else
		switch (size) {
			case 1 : val.bot = get_data_byte (loc); break;
			case 2 : val.bot = get_data_word (loc); break;
			case 4 : val.bot = get_data_long (loc); break;
			case 8 : val = get_data_quad (loc); break;
		}
	return val;
}

static void put (sect, size, loc, val)
int	sect, size;
Quad  loc, val;
{
	if (sect == CS)
		switch (size) {
			case 1 : put_code_byte (loc, (byte)val.bot&0xff); break;
			case 2 : put_code_word (loc, (word)val.bot&0xffff); break;
			case 4 : put_code_long (loc, val.bot); break;
			case 8 : put_code_quad (loc, val); break;
		}
	else
		switch (size) {
			case 1 : put_data_byte (loc, (byte)val.bot&0xff); break;
			case 2 : put_data_word (loc, (word)val.bot&0xffff); break;
			case 4 : put_data_long (loc, val.bot); break;
			case 8 : put_data_quad (loc, val); break;
		}
}

static void put_here (val, size)
Quad	val;
int	size;
{
	if (size > 0) {
		put (csn, size, curr_pos, val); 
		curr_pos = qadd (curr_pos, i2q(size));
	}
	else {			/* pick the proper size */
		if (csn == DS) { /* in the data section */
			put (csn, 1, curr_pos, val); curr_pos = qadd (curr_pos, q1);
		}
		else if (arg_pos >= instrs[yylval].no_arg) {	/* an instr */
			put (csn, 1, curr_pos, i2q (yylval = val.bot)); 
			curr_pos = qadd (curr_pos, q1);
			arg_pos = 0;
		}
		else {
			size = instrs[yylval].arg_size[arg_pos];
			put (csn, size, curr_pos, val);
			curr_pos = qadd (curr_pos, i2q(size)); arg_pos ++;
		}
	}
}

yyerror (s)
char	*s;
{
	fprintf (stderr, "%s at text %s on line %d\n", s, yytext, line_no);
}

static int nf;
static char *files[20];

int yywrap()
{	int i;
	Sect[csn].pos = curr_pos;
	if (nf != 0) {
		Quad cssz, dssz;
		cssz = qsub (Sect[CS].pos, Sect[CS].load);
		dssz = qsub (Sect[DS].pos, Sect[DS].load);
		printf ("; size: CS %d, DS %d\n", cssz.bot, dssz.bot);
	}
	while (files[nf] != 0L) {
		printf ("Loading file %s", files[nf]);
		line_no = 1;
		if ((yyin = fopen(files[nf++], "r")) == NULL) {
			printf ("--bad file name\n"); continue; }
		Sect[CS].load = Sect[CS].pos; Sect[DS].load = Sect[DS].pos; 
		csn = CS; load_addr = curr_pos = Sect[CS].pos; 
		printf ("--load: CS %d, DS %d", Sect[CS].load.bot, Sect[DS].load.bot);
		return 0;
	}
	printf ("Entry point: %d\n", entry.bot);
	for (i = 1; i <= pos; i++) {
		STentry	*p = &ST[i];
		if (p->fptr != 0L) 
			printf ("Symbol %s used and undefined\n", p->name);
	}
	return 1;
}

void get_load_files()
{
	int i = 0; char ch = getchar();
	while (-1) {
		char *p = (char*)malloc(20); int j = 0;
		while (ch == ' ' || ch == '\t') ch = getchar();
		if (ch == '\n') break;
		do {p[j] = ch; j++; } while (!isspace(ch=getchar()));
		p[j] = '\000'; files[i++] = p;
	}
	files[i] = 0L; nf = 0; yyin = fopen ("/dev/null", "r");
}

void initial_load_files(argc, argv)
int	argc;
char	*argv[];
{
	int i = 1;
	for (i; i<argc; i++){
		files[i-1] = argv[i];
	}
	files[i] = 0L; nf = 0; yyin = fopen ("/dev/null", "r");
}

void init_load ()
{	csn = CS; rs =  CS; 
	curr_pos = q0; load_addr = q0;
	Sect[0].pos = Sect[0].load = Sect[1].pos = Sect[1].load = q0;
	pos = 0; /* reset ST */
	entry = q0;
}

